-- StudyPilot Ver.1 initial database schema
-- Target database: PostgreSQL

CREATE TABLE goal (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    target_date     DATE,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_goal_status
        CHECK (status IN ('ACTIVE', 'COMPLETED', 'PAUSED'))
);

CREATE TABLE category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id         BIGINT NOT NULL,
    name            VARCHAR(100) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_category_goal
        FOREIGN KEY (goal_id) REFERENCES goal(id) ON DELETE CASCADE,
    CONSTRAINT uq_category_goal_name
        UNIQUE (goal_id, name)
);

CREATE TABLE study_plan (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id         BIGINT NOT NULL,
    title           VARCHAR(255) NOT NULL,
    target_value    INTEGER,
    current_value   INTEGER NOT NULL DEFAULT 0,
    unit            VARCHAR(30),
    due_date        DATE,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_study_plan_goal
        FOREIGN KEY (goal_id) REFERENCES goal(id) ON DELETE CASCADE,
    CONSTRAINT chk_study_plan_values
        CHECK (
            (target_value IS NULL OR target_value >= 0)
            AND current_value >= 0
        ),
    CONSTRAINT chk_study_plan_status
        CHECK (status IN ('ACTIVE', 'COMPLETED', 'PAUSED'))
);

CREATE TABLE study_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id             BIGINT NOT NULL,
    category_id         BIGINT,
    study_date          DATE NOT NULL,
    duration_minutes    INTEGER NOT NULL,
    content             TEXT NOT NULL,
    question_count      INTEGER,
    correct_count       INTEGER,
    incorrect_count     INTEGER,
    memo                TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_study_log_goal
        FOREIGN KEY (goal_id) REFERENCES goal(id) ON DELETE CASCADE,
    CONSTRAINT fk_study_log_category
        FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE SET NULL,
    CONSTRAINT chk_study_log_duration
        CHECK (duration_minutes > 0),
    CONSTRAINT chk_study_log_question_counts
        CHECK (
            (question_count IS NULL OR question_count >= 0)
            AND (correct_count IS NULL OR correct_count >= 0)
            AND (incorrect_count IS NULL OR incorrect_count >= 0)
            AND (
                question_count IS NULL
                OR COALESCE(correct_count, 0) + COALESCE(incorrect_count, 0) <= question_count
            )
        )
);

-- Prevent a study log from using a category that belongs to another goal.
CREATE OR REPLACE FUNCTION validate_study_log_category()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.category_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM category
        WHERE id = NEW.category_id
          AND goal_id = NEW.goal_id
    ) THEN
        RAISE EXCEPTION 'category_id must belong to the specified goal_id';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validate_study_log_category
BEFORE INSERT OR UPDATE OF goal_id, category_id ON study_log
FOR EACH ROW
EXECUTE FUNCTION validate_study_log_category();

-- Keep updated_at current whenever a row changes.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_goal_updated_at
BEFORE UPDATE ON goal
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_category_updated_at
BEFORE UPDATE ON category
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_study_plan_updated_at
BEFORE UPDATE ON study_plan
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_study_log_updated_at
BEFORE UPDATE ON study_log
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX idx_category_goal_id ON category(goal_id);
CREATE INDEX idx_study_plan_goal_id ON study_plan(goal_id);
CREATE INDEX idx_study_log_goal_date ON study_log(goal_id, study_date DESC);
CREATE INDEX idx_study_log_category_id ON study_log(category_id);
